project:
  type: website

website:
  title: "[Seabuck]{.headers}"
  navbar:
    right:
      - href: about.qmd
        text: "[FAQ]{.subheaders}"

format:
  html:
    theme: 
      - styles.scss
    toc: true

execute:
  freeze: auto


