project:
  type: website

website:
  title: "[Seabuck]{.headers}"
  navbar:
    right:
      - href: about.qmd
        text: "[FAQ]{.subheaders}"
      - href: ama.qmd
        text: "[Ask Us Anything]{.subheaders}"
  google-analytics: "G-KYMFWQFDG3"
  favicon: posts/pics/wave-favicon.png

format:
  html:
    theme: 
      - styles.scss
    toc: true

execute:
  freeze: auto


