---
title: "[Land Log: 2024-02-13]{.subheaders}"
draft: false
---

::: {.div .bodyfont}

Last day at work today--a wild feeling to say the least! Projects kept me busy up until the very end, and I'm very grateful to my coworkers who are supportive and helping to pick up some of my regular duties so I can head out to sea. 

Now it's time to finish packing, introduce myself to my fellow science party pals (via email), read up on what sorts of creatures we'll be collecting^[And how we do the collecting--so far I gather that A LOT of trays, buckets, and other forms of containers are essential for success.], and generally organize a few life details.^[Namely: vote, clean up my room, submit my taxes, and tell my MA pals farewell for now.]

----
*Sea fun fact of the day:* [Pyrosomes](https://en.wikipedia.org/wiki/Pyrosome) are likely going to be a creature I'll become very familiar with in the next month. I just learned of their existence yesterday and apparently these things can get [MASSIVE](https://www.youtube.com/watch?v=5EQGA_4BZ5s)^[I think the ones we'll be dealing with are on the centimeter scale... but I'll of course keep my eyes peeled.].

:::