---
title: "[Sea Log: 2024-03-13]{.subheaders}"
draft: false
date: 2024-03-13
---

::: {.div .bodyfont}

A very stormy day. But storms are a bit deceiving out here because it'll look stunningly beautiful, but it'll be hella, hella windy. With big waves and choppy seas. 

Most science got cancelled due to adverse weather conditions (bad to tow stuff if it gets sucked right under the ship from the current).^[For posterity's sake, check out [this video](https://photos.app.goo.gl/SXzhAfcZ8ov1khu78) one of my pals took during processing the CTD bottles]

I slept poorly in the early morning because it was so choppy that it felt like we were literally catching air. With my room right above the bow thrusters at the front, lower decks of the ship, I could hear the sides of the ship thudding down on the water with every wave. Less soothing rocking I'll say. In case anyone's wondering, being in rough seas is kind of like being on a roller coaster. But you don't get to pick when it ends and kinda just have to get on with life until the ocean decides it's done making a scene. It's sort of like gravity changing--suddenly too much gravity, then not enough gravity, and the shifts between the two states are rather dramatic and forceful. Weeeeee



*Sea fun fact of the day:*  Ratchet straps are hefty but not that hefty when the motion of the ocean decides to take over. Our Bongo net escaped out of its strap and started drifting away down the deck! Yikes! Luckily Madison was out there to rescue the net and bring it into the hanger. The plastic picnic table also didn't survive the waves; those benches are very much warped at this point. 


:::