---
title: "[Random notes]{.subheaders}"
draft: true
---
I AM NUMBER 37 ROLL CALL

put phone comp in airplane mode when not using Internet

No quotas, but be mindful. Calls occasionally prob ok

No proprietary data so we can download later and do stuff. Will get shipboard acct, can access later too - see whiteboard for more info



Post Capt stuff on diff page to add to logs later. Don't wanna make jealous

Max speed is 16 knots, when all 4 engines going, when first launched from dry dock when built. Full throttle. Now they go about 12 knots, or at least that's what they tell sci party to use in calculations
Will be in whoi June 11
I drove. Wavy line oops about 645
Mid sunrise



Revelle will be in woods hole 6/11. Capt Wakefield onboarding. Maybe bring parentals and max?

used this for the form submission and event handler to redirect the user after form submit
https://github.com/levinunnink/html-form-to-google-sheet
https://github.com/levinunnink/html-form-to-google-sheet/issues/17


3/14/24 notes:
When u talk about ur love life at midnight and get advice from ppl u met only a lil bit ago
Andrew, grace, and amber agree that our anniversary is first outing date we went on after deciding we should go on dates. So nov 18 for maps and brunch I think 

the ppl who have shit/pissed on the floor and they had to put up signs. whoa. Also andrew, grace, and I must be friends now. we talked about poop!

Journal, whales read
Haven't lived till dance on deck at 2am with the hose as rain. Wee
Leona/lera octo, accidentally ripped off some suckers and ate them
Sunset and sunrise. Omelet hit. Chocolate chickpea for dessert